# Generated by Django 4.2.2 on 2023-06-15 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleblock',
            name='block_body',
        ),
        migrations.RemoveField(
            model_name='article',
            name='image_block',
        ),
        migrations.RemoveField(
            model_name='article',
            name='video_block',
        ),
        migrations.AddField(
            model_name='article',
            name='image_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.photo'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blog.video'),
        ),
    ]
