# Generated by Django 4.2.2 on 2023-06-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_articleblock_block_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='article_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
        migrations.AlterField(
            model_name='video',
            name='article_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article'),
        ),
    ]
