# Generated by Django 4.2.2 on 2023-06-19 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_articles_videos_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='article',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='article',
        ),
        migrations.AlterField(
            model_name='articleblock',
            name='article_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.article'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='article_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='blog.article'),
        ),
        migrations.AlterField(
            model_name='video',
            name='article_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='blog.article'),
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
