# Generated by Django 4.2.2 on 2023-06-14 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('schema', models.ImageField(upload_to='catalog/media/', verbose_name='Схема этажа')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название дома')),
                ('area', models.FloatField(verbose_name='Площадь дома')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('building_type', models.CharField(choices=[('Сруб', 'Сруб'), ('Кирпичные дома', 'Кирпичные дома'), ('Каркасные дома', 'Каркасные дома')], max_length=100, verbose_name='Тип постройки')),
                ('floors', models.IntegerField(verbose_name='Этажи')),
                ('rooms', models.IntegerField(verbose_name='Количество комнат')),
                ('bathrooms', models.IntegerField(verbose_name='Санузлы')),
                ('style', models.CharField(max_length=100, verbose_name='Стиль')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название комнаты')),
                ('area', models.FloatField(verbose_name='Количество квадратных метров')),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='catalog.floorplan')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='catalog.house')),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/media/', verbose_name='Изображение')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.house')),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalog/media/', verbose_name='Изображение')),
                ('floor_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.floorplan')),
            ],
        ),
        migrations.AddField(
            model_name='floorplan',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='catalog.house'),
        ),
    ]
