# Generated by Django 4.2.2 on 2023-06-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='schema',
        ),
        migrations.AddField(
            model_name='floorplan',
            name='schema',
            field=models.ImageField(default='empty', upload_to='floor_plans/', verbose_name='Схема этажа'),
            preserve_default=False,
        ),
    ]
